name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-slim

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      # add Socket Firewall to the runner environment
      - uses: socketdev/action@v1
        with:
          mode: firewall
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: sfw pnpm install

      - name: Lint
        if: matrix.node-version == '24.x'
        run: pnpm lint

      - run: pnpm run build

      - name: Test
        if: matrix.node-version != '24.x'
        run: pnpm vitest run

      - name: Test with coverage
        if: matrix.node-version == '24.x'
        run: pnpm vitest run --coverage

      - name: Upload coverage reports to Codecov
        if: matrix.node-version == '24.x' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5.5.2
        with:
          files: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
